expense app/website/auth.py
from flask import Blueprint, render_template, request,flash,redirect,url_for
from .models import User
from . import db
from .views import views
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        bank_balance = float(request.form.get('bank_balance'))
        confirm_bank_balance=float(request.form.get('confirm_bank_balance'))
        user = User.query.filter_by(email=email).first()
        flash_messages = []

        if user:
            flash_messages.append('Email already exists.')

        if password != confirm_password:
            flash_messages.append('Passwords do not match!')

        if confirm_bank_balance != bank_balance:
            flash_messages.append('Bank balance does not match')

        if bank_balance <= 0:
            flash_messages.append('Invalid amount!')

        if not flash_messages:
            new_user = User(email=email, username=username, bank_balance=bank_balance, password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect(url_for('views.transaction'))
        
        
        for message in flash_messages:
            flash(message, 'error')

    return render_template('sign_up.html')

@auth.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password,password):
                login_user(user, remember=True)
                return redirect(url_for('views.dashboard'))
            else:
                flash('Incorrect Password.','error')
        else:
            flash('Email doesnt exist.','error')


    return render_template('login.html')

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

expense app/website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from .models import Expense
from website import db
from flask_login import login_required, current_user
from datetime import datetime, timedelta


views = Blueprint('views', __name__)

def current_balance(user):
    expenses = Expense.query.filter_by(user_id=user.id).order_by(Expense.date).all()
    current_balance = user.bank_balance

    for expense in expenses:
        if expense.amount_type == 'debit':
            current_balance -= expense.amount
        elif expense.amount_type == 'credit':
            current_balance += expense.amount

    return current_balance


@views.route('/transaction', methods=['GET', 'POST'])
@login_required
def transaction():
    expenses = Expense.query.filter_by(user_id=current_user.id).order_by(Expense.date.desc()).all()
    total_balance = current_balance(current_user)

    return render_template('transaction.html', expenses=expenses, total_balance=total_balance,current_user=current_user)

@views.route('/expense/delete/<int:expense_id>', methods=['POST'])
@login_required
def delete_expense(expense_id):
    expense = Expense.query.get(expense_id)
    if expense:
        db.session.delete(expense)
        db.session.commit()
        flash('Expense deleted successfully!', 'success')
    referring_page = request.referrer
    return redirect(referring_page)

@views.route('/add_expense', methods=['GET','POST'])
@login_required
def add_expense():
    expenses = Expense.query.filter_by(user_id=current_user.id).order_by(Expense.date.desc()).all()
    expenses = expenses[:5] 
    total_balance = current_balance(current_user)
    return render_template('add_expense.html',expenses=expenses,total_balance=total_balance,current_user=current_user)

@views.route('/adding_expense', methods=['POST'])
@login_required
def adding_expense():
    if request.method == 'POST':
        amount = request.form.get('amount')
        amount_type = request.form.get('amount_type')
        description = request.form.get('description')
        date = request.form.get('date')
        input_date = datetime.strptime(date, '%Y-%m-%d').date()
        total_balance = current_balance(current_user)-float(amount)
        if float(amount)<=0:
            flash('Invalid Amount!','error')
        if total_balance<0:
            flash('Invalid Amount!','error')
        else:
            new_expense = Expense(amount=amount, description=description, date=input_date,amount_type=amount_type, user_id=current_user.id)
            db.session.add(new_expense)
            db.session.commit()
            flash('Expense added successfully!', 'success')
    return redirect(url_for('views.add_expense'))

def get_current_balance_data(day,user_id):
    current_balance_dates = []
    balances = []
    current_balance = 0

    for i in range(day-1, -1, -1):
        starting_date = (datetime.now().date() - timedelta(days=i)).strftime('%Y-%m-%d')

        expenses = Expense.query.filter(
            Expense.user_id == user_id,
            Expense.date <= starting_date
        ).order_by(Expense.date).all()

        current_balance = current_user.bank_balance

        for expense in expenses:
            if expense.amount_type == 'debit':
                current_balance -= expense.amount
            elif expense.amount_type == 'credit':
                current_balance += expense.amount

        current_balance_dates.append(starting_date)
        balances.append(current_balance)

    return current_balance_dates, balances


def get_credit_data(day,user_id):
    credit_dates = []
    credits_list = []

    for i in range(day-1, -1, -1):
        starting_date = (datetime.now().date() - timedelta(days=i)).strftime('%Y-%m-%d')
        credit = db.session.query(db.func.sum(Expense.amount)).filter(
            Expense.user_id == user_id,
            Expense.date == starting_date,
            Expense.amount_type == 'credit'
        ).scalar()
        if credit is None:
            credit = 0

        credit_dates.append(starting_date)
        credits_list.append(credit)

    return credit_dates, credits_list


def get_debit_data(day,user_id):
    debit_dates = []
    debit_list = []

    for i in range(day-1, -1, -1):
        starting_date = (datetime.now().date() - timedelta(days=i)).strftime('%Y-%m-%d')
        debit = db.session.query(db.func.sum(Expense.amount)).filter(
            Expense.user_id == user_id,
            Expense.date == starting_date,
            Expense.amount_type == 'debit'
        ).scalar()
        if debit is None:
            debit = 0

        debit_dates.append(starting_date)
        debit_list.append(debit)

    return debit_dates, debit_list


@views.route('/dashboard')
@login_required
def dashboard():
    user_id = current_user.id

    current_balance_dates, balances = get_current_balance_data(3,user_id)
    credit_dates, credits_list = get_credit_data(3,user_id)
    debit_dates, debit_list = get_debit_data(3,user_id)

    return render_template("dashboard.html",
                           current_balance_dates=current_balance_dates,
                           balances=balances,
                           credit_dates=credit_dates,
                           credits_list=credits_list,
                           debit_dates=debit_dates,
                           debit_list=debit_list,
                           current_user=current_user)


@views.route("/analytics", methods=['POST', 'GET'])
@login_required
def analytics():
    user_id = current_user.id
    day_range = int(request.form.get('day_range', 7))
   
    current_balance_dates, balances = get_current_balance_data(day_range, user_id)
    credit_dates, credits_list = get_credit_data(day_range, user_id)
    debit_dates, debit_list = get_debit_data(day_range, user_id)

    return render_template("analytics.html", current_balance_dates=current_balance_dates,
                           balances=balances,
                           credit_dates=credit_dates,
                           credits_list=credits_list,
                           debit_dates=debit_dates,
                           debit_list=debit_list,
                           current_user=current_user)

expense app/website/templates/add_expense.html
<!DOCTYPE html>
<html>
<head>
  <title>Add Expense</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <script src="https://kit.fontawesome.com/93782ebd13.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
  <script>
    setTimeout(function() {
      var flashMessage = document.querySelector('.flash-message');
      if (flashMessage) {
        flashMessage.style.display = 'none';
      }
    }, 2000);
  </script>
</head>
<body>
  <div class="navbar">
    <h1 class="navbar-title">Add Expense</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <ul class="flash-messages">
          {% for category, message in messages %}
            {% if category == 'error' %}
              <li class="flash-message flash-error">{{ message }}</li>
            {% elif category == 'success' %}
              <li class="flash-message flash-success">{{ message }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    {% include 'side_navbar.html' %}
  </div>  
  <div class="container">
    <div class="balance">
      <h3>Current Balance: {{ total_balance }}</h3>
    </div>
    <!-- Expense Form -->
    <form action="{{url_for('views.adding_expense')}}" method="POST">
      <div class="input-group">
        <label for="amount" class="input-group-text">Amount:</label>
        <input type="number" id="amount" name="amount" required>
        <span class="input-icon"><i class="fa-solid fa-indian-rupee-sign"></i></span>
      </div>
      <div class="input-group">
        <div class="type-selection">
          <div class="type-text">Type:</div>
          <div class="radio-selection">
            <label>
              <input type="radio" name="amount_type" value="credit" required>
              <span class="selection-text">Credit</span>
            </label>
            <label>
              <input type="radio" name="amount_type" value="debit" required>
              <span class="selection-text">Debit</span>
            </label>
          </div>
        </div>
      </div>
      <div class="input-group">
        <label for="description" class="input-group-text">Description:</label>
        <textarea id="description" name="description" required></textarea>
      </div>
      <div class="input-group">
        <label for="date" class="input-group-text">Date:</label>
        <input type="date" id="date" name="date" required>
      </div>
      <div class="input-group">
        <input type="submit" class="btn" value="Add Expense">
      </div>
    </form>
    <!-- Expense Table -->
    <h2>Expenses:</h2>
    <table>
      <tr>
        <th>Amount</th>
        <th>Description</th>
        <th>Date</th>
        <th>Type</th>
        <th>Action</th>
      </tr>
      {% if expenses %}
        {% for expense in expenses %}
          <tr>
            <td>
              {% if expense.amount_type == "debit" %}
                <span class="debit">-{{ expense.amount }}</span>
              {% else %}
                <span class="credit">{{ expense.amount }}</span>
              {% endif %}
            </td>
            <td>{{ expense.description }}</td>
            <td>{{ expense.date }}</td>
            <td>
              {% if expense.amount_type == "credit" %}
                <span class="credit">Credit</span>
              {% else %}
                <span class="debit">Debit</span>
              {% endif %}
            </td>
            <td>
              <form action="{{ url_for('views.delete_expense', expense_id=expense.id) }}" method="POST" onsubmit="return confirm('Are you sure you want to delete this expense?');">
                <input type="hidden" name="_method" value="DELETE">
                <button type="submit" class="btn delete-button">
                  <i class="fas fa-trash-alt"></i>
                </button>
              </form>
            </td>
          </tr>
        {% endfor %}
      {% endif %}
    </table>
  </div>
</body>
</html>

expense app/website/templates/analytics.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Dashboard</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='analytics_style.css') }}">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1"></script>
</head>
<body>
  <div class="navbar">
    <h1 class="navbar-title">Analytics</h1>
    {% include 'side_navbar.html' %}
  </div> 
  <div class="canvas-container">
    <h1>
      CURRENT BALANCE GRAPH
    </h1>
    <canvas id="lineChart" width="1200" height="500"></canvas>
  </div>

  <div class="canvas-container">
    <h2>CREDIT GRAPH</h2>
    <canvas id="credit-graph" width="1200" height="500"></canvas>
  </div>

  <div class="canvas-container">
    <h3>DEBIT GRAPH</h3>
    <canvas id="debit-graph" width="1200" height="500"></canvas>
  </div>

  <form action="{{ url_for('views.analytics') }}" method="POST">
    <select name="day_range" id="day_range" class="day_range">
        <option value="7">7 days</option>
        <option value="30">30 days</option>
        <option value="90">90 days</option>
        <option value="365">1 year</option>
    </select>
    <button class="submit_button" type="submit">Submit</button>
</form>

  <script>
    var current_balance_dates = {{ current_balance_dates | safe }};
    var balances = {{ balances | safe }};
    
    var credit_dates = {{ credit_dates | safe }};
    var credits_list = {{ credits_list | safe }};
    
    var debit_dates = {{ debit_dates | safe }};
    var debit_list = {{ debit_list | safe }};
    
    var lineChartCtx = document.getElementById("lineChart").getContext("2d");
    var lineChart = new Chart(lineChartCtx, {
      type: "line",
      data: {
        labels: current_balance_dates,
        datasets: [
          {
            label: "CURRENT BALANCE",
            data: balances,
            fill: false,
            backgroundColor: "rgba(75, 192, 192, 0.5)",
            borderColor: "rgb(75, 192, 192)",
            lineTension: 0.1
          }
        ]
      },
      options: {
        responsive: false,
        scales: {
          y: {
            ticks: {
              color: "rgba(0, 0, 0, 1)" 
            }
          },
          x: {
            ticks: {
              color: "rgba(0, 0, 0, 1)" 
            }
          }
        }
      }
    });

    var creditGraphCtx = document.getElementById("credit-graph").getContext("2d");
    var barChart = new Chart(creditGraphCtx, {
      type: "bar",
      data: {
        labels: credit_dates,
        datasets: [
          {
            label: "CREDIT",
            data: credits_list,
            backgroundColor: "rgba(40, 167, 69, 0.5)",
            borderColor: "rgba(35, 167, 69)",
            borderWidth: 1
          }
        ]
      },
      options: {
        responsive: false,
        scales: {
          y: {
            ticks: {
              color: "rgba(0, 0, 0, 1)" 
            }
          },
          x: {
            ticks: {
              color: "rgba(0, 0, 0, 1)" 
            }
          }
        }
      }
    });

    var debitGraphCtx = document.getElementById("debit-graph").getContext("2d");
    var debitChart = new Chart(debitGraphCtx, {
      type: "bar",
      data: {
        labels: debit_dates,
        datasets: [
          {
            label: "DEBIT",
            data: debit_list,
            backgroundColor: "rgba(255, 87, 87, 0.5)",
            borderColor: "rgba(230, 87, 87)",
            borderWidth: 1
          }
        ]
      },
      options: {
        responsive: false,
        scales: {
          y: {
            ticks: {
              color: "rgba(0, 0, 0, 1)" 
            }
          },
          x: {
            ticks: {
              color: "rgba(0, 0, 0, 1)"
            }
          }
        }
      }
    });

  </script>
</body>
</html>


expense app/website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login_style.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/93782ebd13.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class="flash-container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="flash-message flash-{{ category }}">
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <div class="form-box">
            <div class="logo-container">
                <img src="{{ url_for('static', filename='logo/logo_login.jpg') }}" alt="Logo" class="logo-image">
            </div>
            <h1 id="title">Sign In</h1>
            <form action="{{ url_for('auth.login') }}" method="post">
                <div class="input-group">
                    <div class="form-group">
                        <i class="fa-solid fa-envelope"></i>
                        <label for="email"></label>
                        <input type="email" id="email" name="email" placeholder="Email" required>
                    </div>
                    <div class="form-group">
                        <i class="fa-solid fa-key"></i>
                        <label for="password"></label>
                        <input type="password" id="password" name="password" placeholder="Password" required>
                    </div>
                </div>
                <div class="btn-field">
                    <button type="submit" id="signInBtn">Submit</button>
                </div>
                <div class="donthave">
                    <p>Don't have an account? <a href="{{ url_for('auth.signup') }}">Sign Up</a></p>
                </div>
            </form>
        </div>               
    <script>
        const flashMessages = document.querySelectorAll('.flash-message');
        if (flashMessages) {
            flashMessages.forEach((message) => {
                setTimeout(() => {
                    message.classList.add('fade-out');
                    setTimeout(() => {
                        message.remove();
                    }, 500); 
                }, 2000); 
            });
        }
    </script>
</body>
</html>

expense app/website/templates/side_navbar.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='sidenavbar_style.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <script src="https://kit.fontawesome.com/93782ebd13.js" crossorigin="anonymous"></script>
</head>
<body>
  <div class="sidenav">
    <div class="logo-container">
      <img src="{{ url_for('static', filename='logo/logo.png') }}" alt="Logo" class="logo-image">
    </div>
    <a href="{{url_for('views.dashboard')}}"><i class="fas fa-home"></i> Dashboard</a>
    <a href="{{url_for('views.analytics')}}"><i class="fas fa-chart-bar"></i> Analytics</a>
    <a href="{{url_for('views.transaction')}}"><i class="fas fa-exchange-alt"></i> Transactions</a>
    <a href="{{url_for('views.add_expense')}}"><i class="fas fa-edit"></i> Add Expense</a>
    <a href="{{url_for('auth.logout')}}"><i class="fas fa-sign-out-alt"></i> Log Out</a>
  </div>

  <div class="top-right">
    <div class="user-profile">
      <i class="fas fa-user user-icon"></i>
      <span class="user-name">{{ current_user.username }}</span>
    </div>
  </div>
</body>
</html>

expense app/website/templates/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='signup_style.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/93782ebd13.js" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='transition.js') }}"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <div class="flash-container" style="--flash-count: {{ flash_count }}">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="flash-message">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>                       
        </nav>
        <div class="form-box">
            <h1 id="title">Sign Up</h1>
            <form action="{{ url_for('auth.signup') }}" method="post">
                <div class="input-group">
                    <div class="form-group">
                        <i class="fa-solid fa-user"></i>
                        <label for="username"></label>
                        <input type="text" id="username" name="username" placeholder="Username" required>
                    </div>
                    <div class="form-group">
                        <i class="fa-solid fa-envelope"></i>
                        <label for="email"></label>
                        <input type="email" id="email" name="email" placeholder="Email" required>
                    </div>
                    <div class="form-group">
                        <i class="fa-solid fa-key"></i>
                        <label for="password"></label>
                        <input type="password" id="password" name="password" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <i class="fa-solid fa-key"></i>
                        <label for="confirm_password"></label>
                        <input type="password" id="confirm_password" name="confirm_password" placeholder="Confirm Password" required>
                    </div>
                    <div class="form-group">
                        <i class="fa-solid fa-indian-rupee-sign"></i>
                        <label for="bank_balance"></label>
                        <input type="number" id="bank_balance" name="bank_balance" placeholder="Bank Balance" step="0.01" required>
                    </div>
                    <div class="form-group">
                        <i class="fa-solid fa-indian-rupee-sign"></i>
                        <label for="confirm_bank_balance"></label>
                        <input type="number" id="confirm_bank_balance" name="confirm_bank_balance" placeholder="Confirm Bank Balance" step="0.01" required>
                    </div>
                </div>
                <div class="btn-field">
                    <button type="submit" id="signInBtn">Submit</button>
                </div>
            </form>
            <div class="donthave">
                <p>Already have an account? <a href="{{ url_for('auth.login') }}">Log in</a></p>
            </div>
        </div>
    </div>
    <script>
        const flashMessages = document.querySelectorAll('.flash-message');
    
        if (flashMessages) {
            flashMessages.forEach((message, index) => {
                setTimeout(() => {
                    message.style.transition = 'opacity 0.5s ease';
                    message.style.opacity = '0';
                    message.addEventListener('transitionend', () => {
                        message.remove();
                    });
                }, (index + 1) * 2000);
            });
        }
    </script>    
</body>
</html>


expense app/website/templates/transaction.html
<!DOCTYPE html>
<html>
<head>
  <title>Transaction</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <script>
    setTimeout(function() {
      var flashMessage = document.querySelector('.flash-message');
      if (flashMessage) {
        flashMessage.style.display = 'none';
      }
    }, 2000);
  </script>
</head>
<body>
  <div class="navbar">
    <h1 class="navbar-title">Transaction</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <ul class="flash-messages">
          {% for category, message in messages %}
            {% if category == 'error' %}
              <li class="flash-message flash-error">{{ message }}</li>
            {% elif category == 'success' %}
              <li class="flash-message flash-success">{{ message }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    {% include 'side_navbar.html' %}
  </div>  
  <div class="container">
    <div class="balance">
      <h3>Current Balance: {{ total_balance }}</h3>
    </div>
    <h2>Expense History:</h2>
    <div class="expense-filter">
      <button class="btn" onclick="filterExpenses('debit')">Show Debit</button>
      <button class="btn" onclick="filterExpenses('credit')">Show Credit</button>
      <button class="btn" onclick="filterExpenses('all')">Show All</button>
    </div>
    <table>
      <tr>
        <th>Amount</th>
        <th>Description</th>
        <th>Date</th>
        <th>Type</th>
        <th>Action</th>
      </tr>
      {% for expense in expenses %}
      <tr class="expense-row {% if expense.amount_type == 'debit' %}debit{% elif expense.amount_type == 'credit' %}credit{% endif %}">
        <td>
          {% if expense.amount_type == "debit" %}
            <span class="debit">-{{ expense.amount }}</span>
          {% else %}
            <span class="credit">{{ expense.amount }}</span>
          {% endif %}
        </td>
        <td>{{ expense.description }}</td>
        <td>{{ expense.date }}</td>
        <td>
          {% if expense.amount_type == "credit" %}
            <span class="credit">Credit</span>
          {% else %}
            <span class="debit">Debit</span>
          {% endif %}
        </td>
        <td>
          <form action="{{ url_for('views.delete_expense', expense_id=expense.id) }}" method="POST" onsubmit="return confirm('Are you sure you want to delete this expense?');">
            <input type="hidden" name="_method" value="DELETE">
            <button type="submit" class="btn delete-button">
              <i class="fas fa-trash-alt"></i>
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <script>
    function filterExpenses(type) {
      var expenseRows = document.querySelectorAll('.expense-row');
      if (type === 'debit') {
        expenseRows.forEach(function(row) {
          row.style.display = row.classList.contains('debit') ? 'table-row' : 'none';
        });
      } else if (type === 'credit') {
        expenseRows.forEach(function(row) {
          row.style.display = row.classList.contains('credit') ? 'table-row' : 'none';
        });
      } else if (type === 'all') {
        expenseRows.forEach(function(row) {
          row.style.display = 'table-row';
        });
      }
    }
  </script>
</body>
</html>
